# Create Data

True


In [78]:
from src.utils.synthetic_data_class import _synthetic_data
from src.utils.corruptData import corruptData
import numpy as np
syn_data = _synthetic_data(N=1000, M=20, K=3, p=5, sigma=-9.21, rb=True, a_param=1, b_param=1.5, sigma_std=1e-6)
X = syn_data.X
X_cor, idx1, idx2 = corruptData(data=X.copy(), corruption_rate=0.01, likertScale=5)

In [84]:
sd = _synthetic_data(**{'a_param': 1, 'b_param': 1.5, 'sigma': -9.21, 'sigma_std': 1e-06, 'N': 1000, 'M': 20, 'K': 3, 'rb': True, 'p': 5})

In [53]:
print(f"percent corrupted: {len(np.nonzero(X - X_cor)[0]) / len(X.ravel())}")
X_cor2, _, _ = corruptData(data=X.copy(), corruption_rate=0.01, likertScale=5)

print(f"Is reproducible? {(X_cor2 == X_cor).all()}")

percent corrupted: 0.0084
Is reproducible? True


In [66]:
from src.visualizations.functions import load_analyses, load_result_obj

res_objs = load_analyses('results/synthetic_Q20_RB/')

OAA_anal = res_objs['OAA']['K3'][2]
TSAA_anal = res_objs['TSAA']['K3'][2]

In [63]:
TSAA_anal.X

array([[5.        , 1.87115141, 4.27622838, ..., 4.27622838, 5.        ,
        4.27622838],
       [5.        , 4.27622838, 3.1569473 , ..., 5.        , 4.27622838,
        3.1569473 ],
       [5.        , 1.        , 3.1569473 , ..., 1.87115141, 3.1569473 ,
        3.1569473 ],
       ...,
       [4.27622838, 1.87115141, 3.1569473 , ..., 3.1569473 , 3.1569473 ,
        3.1569473 ],
       [4.27622838, 3.1569473 , 3.1569473 , ..., 4.27622838, 4.27622838,
        1.        ],
       [5.        , 4.27622838, 3.1569473 , ..., 5.        , 5.        ,
        1.        ]])

In [64]:
OAA_anal.X

array([[2, 3, 2, ..., 3, 1, 1],
       [2, 3, 2, ..., 3, 1, 1],
       [2, 3, 2, ..., 2, 1, 1],
       ...,
       [3, 5, 3, ..., 5, 2, 4],
       [2, 3, 2, ..., 3, 1, 2],
       [3, 5, 3, ..., 5, 2, 4]])

In [70]:
TSAA2_res=load_result_obj('CAA_K=3_rep=2')
TSAA2_res.X

array([[5.        , 1.87115141, 4.27622838, ..., 4.27622838, 5.        ,
        4.27622838],
       [5.        , 4.27622838, 3.1569473 , ..., 5.        , 4.27622838,
        3.1569473 ],
       [5.        , 1.        , 3.1569473 , ..., 1.87115141, 3.1569473 ,
        3.1569473 ],
       ...,
       [4.27622838, 1.87115141, 3.1569473 , ..., 3.1569473 , 3.1569473 ,
        3.1569473 ],
       [4.27622838, 3.1569473 , 3.1569473 , ..., 4.27622838, 4.27622838,
        1.        ],
       [5.        , 4.27622838, 3.1569473 , ..., 5.        , 5.        ,
        1.        ]])

In [85]:
from src.utils.synthetic_data_class import _synthetic_data
sd = _synthetic_data(**{"a_param": 1.5, "b_param": 1.0, "sigma": -9.21, "sigma_std": 1e-06, "N": 1000, "M": 20, "K": 3, "p": 5, "rb": True})

In [87]:
sd.X == OAA_anal.X

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])